---
spring:
  profiles:
    active:
    - dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: fr.esupportail.esupstage.configuration.jpa.ESUPPhysicalNamingStrategy
joinfaces:
    jsf:
      PROJECT_STAGE: Development
    primefaces:
      theme: admin
logging:
  level:
    root: WARN
    '[org.springframework]': WARN
    '[org.springframework.boot]': INFO
    '[org.hibernate.SQL]': ERROR
    '[fr.esupportail.esupstage]': INFO
  file:
    path: /home/xxx/logs/esupstage
    name: esupstage.log
    max-history: 365
application:
  title: esupstage
  redirect-url: http://localhost:8080/index.xhtml
  security:
    ldap-user-dn-patterns: uid={0},ou=people,dc=uphf,dc=fr
...
---
spring:
  profiles: ldap
  ldap:
    urls:
    - ldap://ldap.uphf.fr:389
    anonymous-read-only: true
...
---
spring:
  profiles: embedded-ldap
  ldap:
    embedded:
      base-dn:
      - dc=uphf,dc=fr
      validation:
        enabled: false
      credential:
        password: ''
        username: ''
...
---
spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:local_database.db
    driverClassName: org.h2.Driver
    username: ''
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
...
---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/esupstage
    username: ''
    password: ''
  jpa:
    properties:
      '[hibernate.dialect]': org.hibernate.dialect.MariaDB103Dialect
      '[hibernate.dialect.storage_engine]': innodb
...
---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/esupstage
    username: ""
    password: ""
  jpa:
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
...
---
spring:
  profiles: cas
application:
  cas:
    base-url: http://localhost:8085/cas
    call-back-url: http://localhost:8080
    login-end-point: /login
    logout-end-point: /logout
  restService:
    base-url: http://localhost/
    user: ''
    pass: ''
...
